<?php
/** @var object $model */

echo '<pre>';
print_r($model);
echo '</pre>';
?>

<div class="container-tight py-4 my-auto">
    <div class="text-center mb-4">
        <a href="<?= url() ?>" class="navbar-brand navbar-brand-autodark">
            <img src="<?= asset_url('vendor/Tabler/static/logo.svg') ?>" width="110" height="32" alt="Tabler" class="navbar-brand-image">
        </a>
    </div>
    <form class="card card-md" method="post" autocomplete="off" novalidate>
        <div class="card-body">
            <h2 class="card-title text-center mb-4">Create new account</h2>
            <div class="mb-3">
                <label for="first_name" class="form-label">First Name</label>
                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter first name">
                <?php if (!empty($errors['first_name'])): ?>
                    <div class="invalid-feedback d-block">
                        <?= $model->getFirstError('first_name') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="mb-3">
                <label for="last_name" class="form-label">Last Name</label>
                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter last name">
                <?php if (!empty($errors['last_name'])): ?>
                    <div class="invalid-feedback d-block">
                        <?= $model->getFirstError('last_name') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                <?php if (!empty($errors['email'])): ?>
                    <div class="invalid-feedback d-block">
                        <?= $model->getFirstError('email') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <div class="input-group input-group-flat">
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password" autocomplete="off">
                    <span class="input-group-text">
                  <a href="#" class="link-secondary" title="Show password" data-bs-toggle="tooltip">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"/><path d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6"/></svg>
                  </a>
                </span>
                </div>
                <?php if (!empty($errors['password'])): ?>
                    <div class="invalid-feedback d-block">
                        <?= $model->getFirstError('password') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="mb-3">
                <label for="confirm_password" class="form-label">Confirm Password</label>
                <div class="input-group input-group-flat">
                    <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Password" autocomplete="off">
                    <span class="input-group-text">
                  <a href="#" class="link-secondary" title="Show password" data-bs-toggle="tooltip">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"/><path d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6"/></svg>
                  </a>
                </span>
                </div>
                <?php if (!empty($errors['confirm_password'])): ?>
                    <div class="invalid-feedback d-block">
                        <?= $model->getFirstError('confirm_password') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="mb-3">
                <label class="form-check">
                    <input type="checkbox" class="form-check-input"/>
                    <span class="form-check-label">Agree the <a href="<?= url('terms') ?>" tabindex="-1">terms and policy</a>.</span>
                </label>
            </div>
            <div class="form-footer">
                <button type="submit" class="btn btn-primary w-100">Create new account</button>
            </div>
        </div>
    </form>
    <div class="text-center text-secondary mt-3">
        Already have account? <a href="<?= url('login') ?>" tabindex="-1">Sign in</a>
    </div>
</div>